"""empty message

Revision ID: 58ab7d0bc587
Revises: 
Create Date: 2021-01-15 23:20:21.673773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58ab7d0bc587'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kid',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kid_id', sa.String(), nullable=True),
    sa.Column('kid_name', sa.String(), nullable=True),
    sa.Column('kid_email', sa.String(), nullable=True),
    sa.Column('kid_pin', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.String(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('parent_name', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('parent_email', sa.String(), nullable=True),
    sa.Column('parent_password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parent')
    op.drop_table('kid')
    # ### end Alembic commands ###
