"""empty message

Revision ID: 993fd74afdf9
Revises: d0f69d436ddd
Create Date: 2021-01-19 17:25:16.394312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '993fd74afdf9'
down_revision = 'd0f69d436ddd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kid', sa.Column('kid_dob', sa.String(), nullable=True))
    op.add_column('kid', sa.Column('kid_gender', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kid', 'kid_gender')
    op.drop_column('kid', 'kid_dob')
    # ### end Alembic commands ###
