"""empty message

Revision ID: b81843f696d8
Revises: 
Create Date: 2021-01-20 16:14:30.466346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b81843f696d8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kid',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kid_id', sa.String(), nullable=True),
    sa.Column('kid_name', sa.String(), nullable=True),
    sa.Column('kid_dob', sa.String(), nullable=True),
    sa.Column('kid_gender', sa.String(), nullable=True),
    sa.Column('kid_email', sa.String(), nullable=True),
    sa.Column('kid_pin', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('panel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.String(), nullable=True),
    sa.Column('pay_request', sa.Boolean(), nullable=True),
    sa.Column('two_f_auth', sa.Boolean(), nullable=True),
    sa.Column('restrict_bal', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.String(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('parent_name', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('parent_email', sa.String(), nullable=True),
    sa.Column('parent_password', sa.String(), nullable=True),
    sa.Column('acc_status', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parent')
    op.drop_table('panel')
    op.drop_table('kid')
    # ### end Alembic commands ###
